# The minimal profile will install just the core control plane
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
    namespace: istio-system
spec:
  components:
    ingressGateways:

  addonComponents:
    prometheus:
      enabled: false
